---
title: Gebruik een schuifregelaar om een variabele in te stellen
hero_image: images/banner.png
description: Gebruik een schuifregelaar om een variabele in te stellen
version: 4
listed: false
copyedit: false
last_tested: "2021-06-10"
steps:
  - title: Gebruik een schuifregelaar om een variabele in te stellen
