title: scratch3-slider-variable
hero_image: images/banner.png
description: scratch3-slider-variable description
version: 4
listed: false
copyedit: false
last_tested: "2021-06-10"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
