---
title: Defnyddia'r llithrydd i osod newidyn
hero_image: images/banner.png
description: Defnyddia'r llithrydd i osod newidyn
version: 4
listed: false
copyedit: false
last_tested: "2021-06-10"
steps:
  - title: Defnyddia'r llithrydd i osod newidyn
