---
title: Use o controle deslizante para definir a variável
hero_image: images/banner.png
description: Use o controle deslizante para definir a variável
version: 4
listed: false
copyedit: false
last_tested: "2021-06-10"
steps:
  - title: Use o controle deslizante para definir a variável
