---
title: Usar un deslizador para fijar una variable
hero_image: images/banner.png
description: Usar un deslizador para fijar una variable
version: 4
listed: false
copyedit: false
last_tested: "2021-06-10"
steps:
  - title: Usar un deslizador para fijar una variable
