---
title: استخدم المنزلقة لتعيين متغير
hero_image: images/banner.png
description: استخدم المنزلقة لتعيين متغير
version: 4
listed: false
copyedit: false
last_tested: "2021-06-10"
steps:
  - title: استخدم المنزلقة لتعيين متغير
