---
title: Utiliser une barre de défilement pour définir une variable
hero_image: images/banner.png
description: Utiliser une barre de défilement pour définir une variable
version: 4
listed: false
copyedit: false
last_tested: "2021-06-10"
steps:
  - 
    title: Utiliser une barre de défilement pour définir une variable
